language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t hafezbazrafshan/react -f Dockerfile.dev .

script: 
  - docker run -e CI=true hafezbazrafshan/react npm run test
